### ISSUE TITLE
Tekkit 2 Server V1.1.0 endless: Exception caught during firing event ic2.api.energy.event.EnergyTileLoadEvent@

### ISSUE THREAD

**Issue by Lumpous** [xJon/Tekkit-2#125]
openjdk version "1.8.0_342"
OpenJDK Runtime Environment (build 1.8.0_342-8u342-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.342-b07, mixed mode)

After I updated the server and moved only the world from v1.0.5 to v1.1.0, the server starts spamming the console and log files with tons of errors - always the same error:

latest.log: https://mclo.gs/Yqo8DU9
debug.log: https://lumpous.de/debug.log (sorry, to big for mclo.gs)

> [16:18:22] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 4636ms behind, skipping 92 tick(s)
[16:18:23] [Server thread/ERROR] [FML]: Exception caught during firing event ic2.api.energy.event.EnergyTileLoadEvent@57c0f3d8:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_342]
	at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_342]
	at net.minecraft.util.NonNullList.get(SourceFile:44) ~[fi.class:?]
	at ic2.core.energy.EnergyNetLocal.addMetaTileEntity(EnergyNetLocal.java:1413) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EnergyNetLocal.addTile(EnergyNetLocal.java:1377) ~[EnergyNetLocal.class:?]
	at ic2.core.energy.EnergyNetGlobal$EventHandler.onEnergyTileLoad(EnergyNetGlobal.java:384) ~[EnergyNetGlobal$EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_276_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at mods.railcraft.common.plugins.ic2.IC2Plugin.addTileToNet(IC2Plugin.java:63) ~[IC2Plugin.class:?]
	at mods.railcraft.common.blocks.logic.IC2EmitterLogic.addToNet(IC2EmitterLogic.java:96) ~[IC2EmitterLogic.class:?]
	at mods.railcraft.common.blocks.logic.IC2EmitterLogic.lambda$onStructureChanged$2(IC2EmitterLogic.java:86) ~[IC2EmitterLogic.class:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_342]
	at mods.railcraft.common.util.misc.IWorldSupplier.ifWorld(IWorldSupplier.java:35) ~[IWorldSupplier.class:?]
	at mods.railcraft.common.blocks.logic.IC2EmitterLogic.onStructureChanged(IC2EmitterLogic.java:84) ~[IC2EmitterLogic.class:?]
	at mods.railcraft.common.blocks.logic.Logic.lambda$onStructureChanged$4(Logic.java:122) ~[Logic.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_342]
	at mods.railcraft.common.blocks.logic.Logic.onStructureChanged(Logic.java:122) ~[Logic.class:?]
	at mods.railcraft.common.blocks.logic.StructureLogic.changePattern(StructureLogic.java:184) ~[StructureLogic.class:?]
	at mods.railcraft.common.blocks.logic.StructureLogic.lambda$testIfMasterBlock$8(StructureLogic.java:298) ~[StructureLogic.class:?]
	at java.util.HashMap.forEach(HashMap.java:1290) ~[?:1.8.0_342]
	at mods.railcraft.common.blocks.logic.StructureLogic.testIfMasterBlock(StructureLogic.java:298) ~[StructureLogic.class:?]
	at mods.railcraft.common.blocks.logic.StructureLogic.updateServer(StructureLogic.java:250) ~[StructureLogic.class:?]
	at mods.railcraft.common.util.misc.IWorldSupplier.lambda$ifHost$0(IWorldSupplier.java:45) ~[IWorldSupplier.class:?]
	at java.util.Optional.ifPresent(Optional.java:159) [?:1.8.0_342]
	at mods.railcraft.common.util.misc.IWorldSupplier.ifHost(IWorldSupplier.java:45) [IWorldSupplier.class:?]
	at mods.railcraft.common.blocks.logic.Logic.update(Logic.java:94) [Logic.class:?]
	at mods.railcraft.common.blocks.logic.StructureLogic.update(StructureLogic.java:230) [StructureLogic.class:?]
	at mods.railcraft.common.blocks.TileLogic.update(TileLogic.java:71) [TileLogic.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1838) [amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) [oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
[16:18:23] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[16:18:23] [Server thread/ERROR] [FML]: 0: NORMAL
[16:18:23] [Server thread/ERROR] [FML]: 1: ASM: ic2.core.energy.EnergyNetGlobal$EventHandler@170878e9 onEnergyTileLoad(Lic2/api/energy/event/EnergyTileLoadEvent;)V
[16:18:23] [Server thread/ERROR] [railcraft]: IC2 API error, please update your mods. Error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[16:18:23] [Server thread/ERROR] [railcraft]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[16:18:23] [Server thread/ERROR] [railcraft]: java.util.ArrayList.rangeCheck(ArrayList.java:659)
[16:18:23] [Server thread/ERROR] [railcraft]: java.util.ArrayList.get(ArrayList.java:435)
[16:18:23] [Server thread/ERROR] [railcraft]: IC2 API error: EnergyTileLoadEvent is loaded from jar:file:/home/gameserver/tekkit2_v110/./mods/IC2Classic%201.12-1.5.5.2.1.jar!/ic2/api/energy/event/EnergyTileLoadEvent.class

I guess I will stay on v1.0.5 for a few more days ;)

**Comment by xJon** [comment]
Seems to be the same issue as https://github.com/Railcraft/Railcraft/issues/2040.

**Comment by xJon** [comment]
@Speiger can you provide any insight to this issue? (caused when using Railcraft's latest versions)

**Comment by Speiger** [comment]
This is most likely due to a feedback loop.
IC2C throws block updates on every block that gets added to the enet (cables need that) and i assume railcraft doesn't have a protection for that. or doesn't account for that.

**Comment by lividsubset3** [comment]
Where is latest server download, or is it more of a full manual update?

**Comment by xJon** [comment]
Should be resolved in `1.1.1` thanks to @Speiger's fix https://github.com/Railcraft/Railcraft/pull/2086  :)
