### ISSUE TITLE
Issue with launching server. 

### ISSUE THREAD

**Issue by Irodo** [xJon/Tekkit-2#153]
Hiya,

Just having an issue launching the server from a fresh install. I have the most updated version of Java 8 yet I get this error when launching the .bat file:

`A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 3 more`

Thanks in advance,

**Comment by xJon** [comment]
You need to have Java 8, 64 bit installed on your computer - it is detecting a JDK version instead.

**Comment by Irodo** [comment]
All sorted now... I had an old version of JDK installed that I wasn't aware of.

Thank you kindly - I love the work you do :)
