### ISSUE TITLE
Server Error When Launching

### ISSUE THREAD

**Issue by deac05** [xJon/Tekkit-2#241]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Help needed**

When launching server command prompt comes up with this error

[Tekkit 2] Server is starting...
[Tekkit 2] Hopefully you're running Java 8!
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:109)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 3 more
Press any key to continue . . .

**Comment by xJon** [comment]
You need to make sure you have Java 8 installed. You can get more support for this over Technic's Discord: https://discord.com/invite/technic

**Comment by deac05** [comment]
I have these installed is this not the right version of java?
![Screenshot 2024-02-12 123553](https://github.com/xJon/Tekkit-2/assets/78194625/8231a5d7-5356-4817-bc23-6957ccf45884)

**Comment by xJon** [comment]
The last one is not - if you don't need it for other purposes, you can uninstall it.

**Comment by xJon** [comment]
Closing due to inactivity.
